# Generated by Django 4.1.7 on 2023-03-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='automatic insertation of record')),
                ('modified', models.DateTimeField(auto_now=True, help_text='automatic modification of record')),
                ('title', models.CharField(help_text='this is socialmedia like instagram', max_length=100, unique=True)),
                ('url', models.URLField(help_text='url of socialmedia', max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
