# Generated by Django 4.1.7 on 2023-03-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='automatic insertion of record'),
        ),
    ]
