# Generated by Django 4.1.7 on 2023-03-02 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='automatic insertation of record')),
                ('modified', models.DateTimeField(auto_now=True, help_text='automatic modification of record')),
                ('title', models.CharField(help_text='category name', max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='automatic insertation of record')),
                ('modified', models.DateTimeField(auto_now=True, help_text='automatic modification of record')),
                ('height_field', models.PositiveSmallIntegerField(blank=True, editable=False, help_text='photos height', null=True)),
                ('width_field', models.PositiveSmallIntegerField(blank=True, editable=False, help_text='photos width', null=True)),
                ('alternate_text', models.CharField(help_text='describe about photo that is uoloaded.please write a good description for search engines', max_length=110)),
                ('title', models.CharField(help_text='product name', max_length=20, unique=True)),
                ('description', models.TextField(help_text='explain about product', unique=True)),
                ('size', models.PositiveIntegerField(help_text='size of product')),
                ('picture', models.ImageField(height_field='height_field', help_text='photo of product', max_length=110, unique=True, upload_to='product/', width_field='width_field')),
                ('category', models.ForeignKey(help_text='related to product', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
