# Generated by Django 4.1.7 on 2023-03-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='automatic insertion of record'),
        ),
        migrations.AlterField(
            model_name='product',
            name='alternate_text',
            field=models.CharField(help_text='describe about photo that is uploaded.please write a good description for search engines', max_length=110),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='automatic insertion of record'),
        ),
    ]
