# Generated by Django 4.1.7 on 2023-03-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='automatic insertion of record')),
                ('modified', models.DateTimeField(auto_now=True, help_text='automatic modification of record')),
                ('title', models.CharField(help_text='how it work title', max_length=20, unique=True, verbose_name='Title')),
                ('picture', models.ImageField(height_field='height_field', max_length=110, upload_to='submitorder/', verbose_name='picture', width_field='width_field')),
                ('height_field', models.PositiveSmallIntegerField(blank=True, editable=False, help_text='size of the picture height ', null=True, verbose_name='height_field')),
                ('width_field', models.PositiveSmallIntegerField(blank=True, editable=False, help_text='size of the picture height ', null=True, verbose_name='width_field')),
                ('alternate_text', models.CharField(help_text='alter text for submit order picture', max_length=110)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
