Table AboutUs as AU {
  id int [pk, increment]
  title varchar(20) [unique,not null]
  description text [unique,not null]
  image image [not null]
  image2 image [not null]
  video file [not null]
  created timestamptz [not null]
  modifeid timestamptz [not null]
}

Table Contact as C {
  id int [pk, increment]
  name varchar(100) [not null]
  email varchar(100) [unique,not null]
  phone varchar(20) [unique,not null]
  subject varchar(50)
  message text [not null]
  created timestamptz [not null]
  modifeid timestamptz [not null]
}

Table SocialMedia as SM {
  id int [pk, increment]
  title varchar(20) [unique,not null]
  url url
  icon varchar [not null]
  created timestamptz [not null]
  modifeid timestamptz [not null]
}

Table Category as CAT {
  id int [pk, increment]
  title varchar(20) [unique,not null]
  created timestamptz [not null]
  modifeid timestamptz [not null]
}

Table Product as P {
  id int [pk, increment]
  title varchar(20) [unique,not null]
  image image [unique,not null]
  summary text [unique,not null]
  description text [unique,not null]
  size varchar(20) [not null]
  material varchar [not null]
  Category int [ref: > CAT.id]
  created timestamptz [not null]
  modifeid timestamptz [not null]
}


// to do 
Table HowItWork as HIW {
  id int [pk, increment]
  title varchar(20) [unique,not null]
  description text [unique,not null]
  priority int [unique, not null]
  image image [unique,not null]
  created timestamptz [not null]
  modifeid timestamptz [not null]
}

Table Banner as B {
  id int [pk, increment]
  title varchar(20) [not null]
  image image [unique,not null]
  created timestamptz [not null]
  modifeid timestamptz [not null]
}

Table SubmitOrder as SO {
  id int [pk, increment]
  title varchar(20) [not null]
  image image [unique,not null]
  created timestamptz [not null]
  modifeid timestamptz [not null]
}